# Generated by Django 4.0.5 on 2022-06-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_id', models.IntegerField(blank=True)),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
