# Generated by Django 4.0.5 on 2022-06-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='username_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
