# Generated by Django 4.0.5 on 2022-06-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper_app', '0002_alter_tweets_username_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usernames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
