# Generated by Django 4.0.5 on 2022-06-19 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_scraper_app', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='favorite_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='retweet_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='tweet_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='username_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usernames',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usernames',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
